check: tests
	diff reference output
ipsum=exalted packets ampuls flipped zaniest rump whose fiscal tank billowy blamer litchis immure woolies crafted staidly funnily inveigh marshes teaks

tests:
	rm -rf output/*
	../kernagic input/SansGuiltDB.ufo -m original -T '$(ipsum)' -P output/original.png
	../kernagic input/SansGuiltDB.ufo -m cadence  -T '$(ipsum)' -P output/cadence.png
	../kernagic input/SansGuiltDB.ufo -m gap -p 10.93  -T '$(ipsum)' -P output/gap.png
	../kernagic input/SansGuiltDB.ufo -m bounds   -T '$(ipsum)' -P output/bounds.png
