check: tests
	diff reference output
ipsum=exalted packets ampuls flipped zaniest rump whose fiscal tank billowy blamer litchis immure woolies crafted staidly funnily inveigh marshes teaks

tests:
	rm -rf output/*
	../kernagic input/SansGuiltDB.ufo -m original -s '$(ipsum)' -p output/original.png
	../kernagic input/SansGuiltDB.ufo -m cadence  -s '$(ipsum)' -p output/cadence.png
	../kernagic input/SansGuiltDB.ufo -m gap -c 10.93  -s '$(ipsum)' -p output/gap.png
	../kernagic input/SansGuiltDB.ufo -m bounds   -s '$(ipsum)' -p output/bounds.png
